export { default as Welcome } from './Welcome';
export { default as Contacts } from './Contacts';
export { default as Logins } from './Logins';
export { default as ForPassword } from './Forpassword';
export { default as Homes } from './Homes';
export { default as Usercomplaint } from './Usercomplaint';
export { default as Welcomeadmin } from './Welcomeadmin';
export { default as Signup } from './Signup';
export { default as Admcomred } from './Admcomred';
export { default as ResetPass } from './ResetPass'
